In [1]:
import pandas as pd

In [30]:
data1 = {
    "name":["umesh","prince","vikas"],
    "english":[29,28,29],
    "hindi":[29,29,30]
}
data = pd.DataFrame(data1)

In [31]:
print(data)

     name  english  hindi
0   umesh       29     29
1  prince       28     29
2   vikas       29     30

In [32]:
data["average"] = (data["english"] + data["hindi"])/2

In [33]:
data["result"] = data["average"].apply(lambda x: "pass" if x > 20 else "fail")

In [35]:
print(data)

     name  english  hindi  average result
0   umesh       29     29     29.0   pass
1  prince       28     29     28.5   pass
2   vikas       29     30     29.5   pass

In [37]:
group = data.groupby("result")

In [40]:
print(group.size())

result
pass    3
dtype: int64

In [43]:
print(group["english"].mean())

result
pass    28.666667
Name: english, dtype: float64

In [48]:
group["hindi"].agg(["mean","count","max","min"])

             mean  count  max  min
result
pass    29.333333      3   30   29

In [49]:
data.describe()

         english      hindi  average
count   3.000000   3.000000     3.00
mean   28.666667  29.333333    29.00
std     0.577350   0.577350     0.50
min    28.000000  29.000000    28.50
25%    28.500000  29.000000    28.75
50%    29.000000  29.000000    29.00
75%    29.000000  29.500000    29.25
max    29.000000  30.000000    29.50